### ISSUE TITLE
Resort Columns

### ISSUE THREAD

**Issue by bstopp** [aemsites/jet2holidays-portugal#12]
![Resorts](https://github.com/user-attachments/assets/6a8bea97-391c-40be-b0a9-fc4b2253374f)

Block should include the title, placeholder the map link at first, will figure out how to address that later.

Authoring should be based on max number displayed on desktop - will impl mobile first and grow accordingly.

**Comment by NicaAlexandru** [comment]
Merged the component: https://github.com/aemsites/jet2holidays-portugal/pull/77
