### ISSUE TITLE
POI Card

### ISSUE THREAD

**Issue by bstopp** [aemsites/jet2holidays-portugal#16]
![POI_Card](https://github.com/user-attachments/assets/52818df9-ec26-484f-a9c6-78fbcb0460c5)

Input: 
* Image
* Title
* Subtitle
* blurb
* Map Link
* LInk

**Comment by NicaAlexandru** [comment]
Same component as `featured resorts:`: https://github.com/aemsites/jet2holidays-portugal/pull/77

We can control the info from authoring
