### ISSUE TITLE
Grid component

### ISSUE THREAD

**Issue by robertnecsoiu** [aemsites/jet2holidays-portugal#45]
![image](https://github.com/user-attachments/assets/e59fde6d-4249-453d-b074-7d8beb62263b)
![image](https://github.com/user-attachments/assets/77c7e40b-49f1-4b65-86f1-430c926d55a7)
![image](https://github.com/user-attachments/assets/69ecdf34-36dd-48a7-8139-c6dd875fdc34)

**Comment by NicaAlexandru** [comment]
Included in simple-cards and complex-cards
