### ISSUE TITLE
Simple Card component

### ISSUE THREAD

**Issue by robertnecsoiu** [aemsites/jet2holidays-portugal#46]
![image](https://github.com/user-attachments/assets/7182ff3e-119b-43a4-a09a-0c4c07b62527)

**Comment by NicaAlexandru** [comment]
This is a simple card that has only an image

**Comment by NicaAlexandru** [comment]
Identified 2 variations:

1. Simple image with text overlay and link

<img width="1437" alt="image" src="https://github.com/user-attachments/assets/d5df6ce5-3bd5-495d-874a-350e22aff4a5">


2. Simple image with text overlay, link and icon

<img width="1383" alt="image" src="https://github.com/user-attachments/assets/cb0e7897-9952-4d80-95cd-e31445b3f9eb">

**Comment by bstopp** [comment]
This duplicates #9
