### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by robertnecsoiu** [aemsites/jet2holidays-portugal#52]
- [ ] #53
- [ ] #54
![image](https://github.com/user-attachments/assets/b5f5db06-7749-4b83-95db-ca165d260d8a)
![image](https://github.com/user-attachments/assets/7f1e793d-c63d-4fb2-bf7c-410a14d4a104)
![image](https://github.com/user-attachments/assets/096785a0-05cb-4644-97b4-0aeffed3592c)

**Comment by NicaAlexandru** [comment]
Can reuse the simple cards component, which has an icon variation: https://github.com/aemsites/jet2holidays-portugal/pull/76
