### ISSUE TITLE
Portugal resorts

### ISSUE THREAD

**Issue by robertnecsoiu** [aemsites/jet2holidays-portugal#55]
- [ ] #57
- [ ] #56
![image](https://github.com/user-attachments/assets/7d4fbb76-934b-4b6e-92ee-adcc8db3b77b)
![image](https://github.com/user-attachments/assets/843fb7cd-6f05-4754-95d6-802d737cbfdc)
![image](https://github.com/user-attachments/assets/c63f1240-3f06-4ca7-a7fc-0398a461b761)
![image](https://github.com/user-attachments/assets/21b7027e-042d-488c-86c4-f54212c11025)

**Comment by NicaAlexandru** [comment]
Duplicates: https://github.com/aemsites/jet2holidays-portugal/issues/12
