### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by bstopp** [aemsites/jet2holidays-portugal#9]
![Regions](https://github.com/user-attachments/assets/5e25a829-8147-461d-823b-13195557a42d)
![Things to do](https://github.com/user-attachments/assets/d40769a7-32a0-45af-a319-aebf9b3d77f0)

Autor input must include:

* Block Title
* Link to secondary view 
* Optional Icon
* Card Title
* Card image

**Comment by NicaAlexandru** [comment]
Implemented simple-cards and complex-cards blocks
